name: Build UI

on:
  push:
    branches: [master]
    paths: ['ui/**']

jobs:
  build-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui-build
          path: ./ui/dist
