name: Build and Deploy to AWS EC2

on:
  push:
    branches: [master]

jobs:
  build-bff:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bff
    steps:
      - uses: actions/checkout@v3

      - name: Install BFF dependencies
        run: npm install

      - name: Build BFF app
        run: npm run build

      - name: Upload BFF artifact
        uses: actions/upload-artifact@v4
        with:
          name: bff-build
          path: ./bff
  build-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui
    steps:
      - uses: actions/checkout@v3

      - name: Install UI dependencies
        run: npm install

      - name: Build UI app
        run: npm run build

      - name: Upload UI artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui-build
          path: ./ui

  deploy:
    runs-on: ubuntu-latest
    needs: [build-bff, build-ui]
    steps:
      - name: Download BFF artifact
        uses: actions/download-artifact@v4
        with:
          name: bff-build
          path: ./bff

      - name: Download UI artifact
        uses: actions/download-artifact@v4
        with:
          name: ui-build
          path: ./ui

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "mkdir -p ~/deploy/bff ~/deploy/ui"
          scp -r ./bff/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/deploy/bff/
          scp -r ./ui/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/deploy/ui/


          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            export DATABASE_HOST=mysql
            export DATABASE_PORT=3306
            export DATABASE_USER=${{ secrets.DATABASE_USER }}
            export DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            export DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            export GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            export GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            export GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            export GOOGLE_CALLBACK_URL=https://api.study-flow.carvalho.dev.br/auth/google/redirect
            export FRONTEND_REDIRECT_URL=https://study-flow.carvalho.dev.br/home
            export CORS_ORIGIN=https://study-flow.carvalho.dev.br
            export VITE_API_BASE_URL=https://api.study-flow.carvalho.dev.br
            export VITE_GEMINI_API_KEY=${{ secrets.VITE_GEMINI_API_KEY }}

            cd ~/deploy/bff
            npm install --omit=dev
            pm2 restart dist/main.js || pm2 start dist/main.js --name bff

            sudo rm -rf /var/www/html/*
            sudo cp -r ~/deploy/ui/* /var/www/html/
          EOF

