name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy app on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/app || git clone https://github.com/${{ github.repository }}.git ~/app && cd ~/app
            git pull origin master
            cd backend && npm install && npm run build && pm2 restart dist/master.js || pm2 start dist/master.js --name bff
            cd ../frontend && npm install && npm run build
            cp -r dist/* /var/www/html/
          EOF
