name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy app on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/app || git clone https://github.com/${{ github.repository }}.git ~/app && cd ~/app
            git pull origin master
            export DATABASE_HOST=mysql
            export DATABASE_PORT=3306
            export DATABASE_USER=${{ secrets.DATABASE_USER }}
            export DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            export DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            export GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            export GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            export GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            export GOOGLE_CALLBACK_URL=https://api.study-flow.carvalho.dev.br/auth/google/redirect
            export FRONTEND_REDIRECT_URL=https://study-flow.carvalho.dev.br/home
            export CORS_ORIGIN=https://study-flow.carvalho.dev.br
            export VITE_API_BASE_URL=https://api.study-flow.carvalho.dev.br
            export VITE_GEMINI_API_KEY=${{ secrets.VITE_GEMINI_API_KEY }}
            cd bff && npm install && npm run build && pm2 restart dist/src/main.js || pm2 start dist/src/main.js --name bff
          EOF
