name: Test BFF

on:
  push:
    paths:
      - 'bff/**'
  pull_request:
    paths:
      - 'bff/**'

jobs:
  test-bff:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bff

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
